<?php

namespace Database\Seeders;

use App\Models\SubCategory;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SubCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     * php artisan db:seed --class=SubCategorySeeder
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '1',
                'category_id'  => '1',
                'name'  => 'ផ្ទះល្វែងជាន់ផ្ទាល់ដី',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '11000',
                'land_filed_fee'  => '2400',
                'total_fee'  => '13400',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '1',
                'category_id'  => '1',
                'name'  => 'ផ្ទះល្វែងជាន់ទី១ឡើងទៅ',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '6000',
                'land_filed_fee'  => '2000',
                'total_fee'  => '8000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '1',
                'category_id'  => '1',
                'name'  => 'ផ្ទះដីឡូតិ៍ធម្មតា',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '14400',
                'land_filed_fee'  => '2900',
                'total_fee'  => '17300',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '1',
                'category_id'  => '1',
                'name'  => 'ផ្ទះដីឡូតិ៍ធម្មតា',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '14400',
                'land_filed_fee'  => '2900',
                'total_fee'  => '17300',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '1',
                'category_id'  => '1',
                'name'  => 'ផ្ទះមិនរៀបរយ',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '4000',
                'land_filed_fee'  => '1000',
                'total_fee'  => '5000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '1',
                'category_id'  => '1',
                'name'  => 'ភូមិគ្រឹះផ្ទៃដីតូចជាង300m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '38600',
                'land_filed_fee'  => '6700',
                'total_fee'  => '45300',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '1',
                'category_id'  => '1',
                'name'  => 'ភូមិគ្រឹះផ្ទៃដីចាប់ពី300m2-600m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '67500',
                'land_filed_fee'  => '9700',
                'total_fee'  => '77200',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '1',
                'category_id'  => '1',
                'name'  => 'ភូមិគ្រឹះផ្ទៃដីធំជាង600m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '1',
                'category_id'  => '2',
                'name'  => 'ផ្ទះល្វែង',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '11200',
                'land_filed_fee'  => '2000',
                'total_fee'  => '13200',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '1',
                'category_id'  => '2',
                'name'  => 'វីឡាភ្លោះ',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '26800',
                'land_filed_fee'  => '4000',
                'total_fee'  => '30800',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '1',
                'category_id'  => '2',
                'name'  => 'វីឡាទោលមានផ្ទៃដីតូចជាង300m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '51500',
                'land_filed_fee'  => '6700',
                'total_fee'  => '58200',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '1',
                'category_id'  => '2',
                'name'  => 'វីឡាទោលមានផ្ទៃដីចាប់ពី300m2ឡើង',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '1',
                'category_id'  => '3',
                'name'  => 'តិចជាង3បន្ទប់/យូនីត',
                'unit'  => '៛/យូនីត.ខែ',
                'monthly_fee'  => '25800',
                'land_filed_fee'  => '3400',
                'total_fee'  => '29200',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '1',
                'category_id'  => '3',
                'name'  => 'ចាប់ពី3បន្ទប់/យូនីត',
                'unit'  => '៛/យូនីត.ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '1',
                'category_id'  => '4',
                'name'  => 'បន្ទប់ជួលឱ្យកម្មករក្នុងស្រុកស្នាក់នៅ',
                'unit'  => '៛/បន្ទប់.ខែ',
                'monthly_fee'  => '3000',
                'land_filed_fee'  => '1000',
                'total_fee'  => '4000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '1',
                'category_id'  => '4',
                'name'  => 'បន្ទប់ជួលឱ្យបរទេសក្នុងស្រុកស្នាក់នៅ',
                'unit'  => '៛/បន្ទប់.ខែ',
                'monthly_fee'  => '18000',
                'land_filed_fee'  => '2000',
                'total_fee'  => '20000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '1',
                'category_id'  => '5',
                'name'  => 'ផ្ទះជួលឱ្យបរទេសស្នាក់នៅ',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'ទ្វេរគុណ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '2',
                'category_id'  => '6',
                'name'  => 'ទំហំផ្ទះ ១ល្វែង ស្ថិតក្នុងតំបន់១',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '66600',
                'land_filed_fee'  => '9000',
                'total_fee'  => '75600',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '2',
                'category_id'  => '6',
                'name'  => 'ទំហំចាប់ពីផ្ទះ ២ល្វែងឡើង ស្ថិតក្នុងតំបន់១',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '2',
                'category_id'  => '6',
                'name'  => 'ទំហំផ្ទះ ១ល្វែង ស្ថិតក្នុងតំបន់២',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '44400',
                'land_filed_fee'  => '6000',
                'total_fee'  => '50400',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '2',
                'category_id'  => '6',
                'name'  => 'ទំហំចាប់ពីផ្ទះ ២ល្វែងឡើង ស្ថិតក្នុងតំបន់២',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '2',
                'category_id'  => '7',
                'name'  => 'អាហារដ្ឋាន ផ្ទះ១ល្វែង ១ជាន់ ក្នុងតំបន់២',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '69900',
                'land_filed_fee'  => '9200',
                'total_fee'  => '79100',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '2',
                'category_id'  => '7',
                'name'  => 'អាហារដ្ឋាន ធំជាងផ្ទះ១ល្វែង ឫលើសពី ១ជាន់ ក្នុងតំបន់២',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '2',
                'category_id'  => '7',
                'name'  => 'អាហារដ្ឋាន ផ្ទះ១ល្វែង ក្នុងតំបន់១',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '106400',
                'land_filed_fee'  => '14000',
                'total_fee'  => '120400',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '2',
                'category_id'  => '7',
                'name'  => 'អាហារដ្ឋាន ធំជាងផ្ទះ១ល្វែង ឫលើសពី ១ជាន់ ក្នុងតំបន់១',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '2',
                'category_id'  => '7',
                'name'  => 'ភោជនីយដ្ឋាន ផ្ទះ១ល្វែង ១ជាន់ ក្នុងតំបន់២',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '131600',
                'land_filed_fee'  => '17200',
                'total_fee'  => '148800',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '2',
                'category_id'  => '7',
                'name'  => 'អាហារដ្ឋាន ធំជាងផ្ទះ១ល្វែង ឫលើសពី ១ជាន់ ក្នុងតំបន់២',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '2',
                'category_id'  => '7',
                'name'  => 'ភោជនីយដ្ឋាន ផ្ទះ១ល្វែង ១ជាន់ ក្នុងតំបន់១',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '185000',
                'land_filed_fee'  => '15000',
                'total_fee'  => '200000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '2',
                'category_id'  => '7',
                'name'  => 'ភោជនីយដ្ឋាន ធំជាងផ្ទះ១ល្វែង ឫលើសពី ១ជាន់ ក្នុងតំបន់១',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            // [
            //     /* false*/
            //     'user_id'  => '1',
            //     'branch_id'  => '1',
            //     'business_type_id'  => '2',
            //     'category_id'  => '7',
            //     'name'  => 'ភោជនីយដ្ឋាន ធំជាងផ្ទះ១ល្វែង ឫលើសពី ១ជាន់ ក្នុងតំបន់១',
            //     'unit'  => '៛/ខែ',
            //     'monthly_fee'  => '0',
            //     'land_filed_fee'  => '0',
            //     'total_fee'  => '0',
            //     'noted'  => 'សមាមាត្រ',
            //     'created_by'  => '1',
            // ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '2',
                'category_id'  => '7',
                'name'  => 'ភោជនីយដ្ឋានប៊ូហ្វេ(គិតផ្ទៃអគារ)',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '2000',
                'land_filed_fee'  => '400',
                'total_fee'  => '2400',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '2',
                'category_id'  => '7',
                'name'  => 'អាហារដ្ឋាន និងខ្ចុះអាហារដ្ឋានតាមឆ្នេរ',
                'unit'  => '៛/ម២.ខែ',
                'monthly_fee'  => '235000',
                'land_filed_fee'  => '15000',
                'total_fee'  => '250000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '2',
                'category_id'  => '7',
                'name'  => 'ភោជនីយដ្ឋានតាមឆ្នេរ តូចជាង500 ម៉ែត្រការ៉េ (គិតផ្ទៃដី)',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '370000',
                'land_filed_fee'  => '30000',
                'total_fee'  => '400000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '2',
                'category_id'  => '7',
                'name'  => 'ភោជនីយដ្ឋានតាមឆ្នេរ តូចជាង500->1000ម៉ែត្រការ៉េ (គិតផ្ទៃដី)',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '750000',
                'land_filed_fee'  => '50000',
                'total_fee'  => '800000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '2',
                'category_id'  => '7',
                'name'  => 'ភោជនីយដ្ឋានតាមឆ្នេរ ធំជាង1000 ម៉ែត្រការ៉េ (គិតផ្ទៃដី)',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '1120000',
                'land_filed_fee'  => '80000',
                'total_fee'  => '1200000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '2',
                'category_id'  => '7',
                'name'  => 'ហាងកាហ្វេទំនើប(គិតផ្ទៃអាគារ)',
                'unit'  => '៛/ម២.ខែ',
                'monthly_fee'  => '2800',
                'land_filed_fee'  => '400',
                'total_fee'  => '3200',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '2',
                'category_id'  => '7',
                'name'  => 'ហាងកាហ្វេទំនើប មានភោជនីយដ្ឋាន(គិតផ្ទៃអាគារ)',
                'unit'  => '៛/ម២.ខែ',
                'monthly_fee'  => '3400',
                'land_filed_fee'  => '600',
                'total_fee'  => '4000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '3',
                'category_id'  => '8',
                'name'  => 'បឹងហ្គាឡូ',
                'unit'  => '៛/បន្ទប់.ខែ',
                'monthly_fee'  => '35200',
                'land_filed_fee'  => '4800',
                'total_fee'  => '40000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '3',
                'category_id'  => '9',
                'name'  => 'មានអាហារដ្ឋាន/ភោជនីយដ្ឋាន(ចំនួន១) ស្ថិតក្នុងតំបន់១',
                'unit'  => '៛/បន្ទប់.ខែ',
                'monthly_fee'  => '44800',
                'land_filed_fee'  => '6400',
                'total_fee'  => '51200',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '3',
                'category_id'  => '9',
                'name'  => 'មានអាហារដ្ឋាន/ភោជនីយដ្ឋាន(ចំនួន២) ស្ថិតក្នុងតំបន់១',
                'unit'  => '៛/បន្ទប់.ខែ',
                'monthly_fee'  => '56000',
                'land_filed_fee'  => '8000',
                'total_fee'  => '64000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '3',
                'category_id'  => '9',
                'name'  => 'មានអាហារដ្ឋាន/ភោជនីយដ្ឋាន(ចំនួន១) ស្ថិតក្នុងតំបន់២',
                'unit'  => '៛/បន្ទប់.ខែ',
                'monthly_fee'  => '26900',
                'land_filed_fee'  => '3800',
                'total_fee'  => '30700',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '3',
                'category_id'  => '9',
                'name'  => 'មានអាហារដ្ឋាន/ភោជនីយដ្ឋាន(ចំនួនចាប់ពី២) ស្ថិតក្នុងតំនប់២',
                'unit'  => '៛/បន្ទប់.ខែ',
                'monthly_fee'  => '33600',
                'land_filed_fee'  => '4800',
                'total_fee'  => '38400',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '3',
                'category_id'  => '9',
                'name'  => 'គ្មានអាហារដ្ឋាន ស្ថិតក្នុងតំបន់១',
                'unit'  => '៛/បន្ទប់.ខែ',
                'monthly_fee'  => '21800',
                'land_filed_fee'  => '3100',
                'total_fee'  => '24900',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '3',
                'category_id'  => '9',
                'name'  => 'គ្មានអាហារដ្ឋាន ស្ថិតក្នុងតំបន់២',
                'unit'  => '៛/បន្ទប់.ខែ',
                'monthly_fee'  => '13400',
                'land_filed_fee'  => '1900',
                'total_fee'  => '15300',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '3',
                'category_id'  => '10',
                'name'  => 'រីសត',
                'unit'  => '៛/បន្ទប់.ខែ',
                'monthly_fee'  => '44800',
                'land_filed_fee'  => '6400',
                'total_fee'  => '51200',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '3',
                'category_id'  => '11',
                'name'  => 'ផ្ទះសំណាក់ ស្ថិតក្នុងតំបន់១',
                'unit'  => '៛/បន្ទប់.ខែ',
                'monthly_fee'  => '12600',
                'land_filed_fee'  => '1800',
                'total_fee'  => '14400',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '3',
                'category_id'  => '11',
                'name'  => 'ផ្ទះសំណាក់ ស្ថិតក្នុងតំបន់២',
                'unit'  => '៛/បន្ទប់.ខែ',
                'monthly_fee'  => '10100',
                'land_filed_fee'  => '1400',
                'total_fee'  => '11500',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '4',
                'category_id'  => '13',
                'name'  => 'ទំហំតូចជាង500m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '88000',
                'land_filed_fee'  => '12000',
                'total_fee'  => '100000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '4',
                'category_id'  => '13',
                'name'  => 'ទំហំចាប់ពី500m2-1000m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '188000',
                'land_filed_fee'  => '12000',
                'total_fee'  => '200000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '4',
                'category_id'  => '13',
                'name'  => 'ទំហំចាប់បី1000m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '4',
                'category_id'  => '13',
                'name'  => 'ទំហំតូចជាង200m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '88000',
                'land_filed_fee'  => '12000',
                'total_fee'  => '100000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '4',
                'category_id'  => '13',
                'name'  => 'ទំហំចាប់ពី200m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '4',
                'category_id'  => '14',
                'name'  => 'ទំហំតូជាង200m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '188000',
                'land_filed_fee'  => '12000',
                'total_fee'  => '200000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '4',
                'category_id'  => '14',
                'name'  => 'ទំហំចាប់ពី200m2-400m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '280000',
                'land_filed_fee'  => '20000',
                'total_fee'  => '300000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '4',
                'category_id'  => '14',
                'name'  => 'ទំហំចាប់បី400m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '5',
                'category_id'  => '15',
                'name'  => 'ទំហំតូចជាង200m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '827400',
                'land_filed_fee'  => '54000',
                'total_fee'  => '881400',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '5',
                'category_id'  => '15',
                'name'  => 'ទំហំចាប់ពី200m2-400m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '1654800',
                'land_filed_fee'  => '108000',
                'total_fee'  => '1762800',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '5',
                'category_id'  => '15',
                'name'  => 'ទំហំចាប់បី400m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '5',
                'category_id'  => '15',
                'name'  => 'KTV ខារ៉ាអូខេ កម្រិតធម្មតា',
                'unit'  => '៛/បន្ទប់.ខែ',
                'monthly_fee'  => '77400',
                'land_filed_fee'  => '5400',
                'total_fee'  => '82800',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '5',
                'category_id'  => '16',
                'name'  => 'ចំណុះតិចជាង ១៥តុ ស្ថិតក្នុងតំបន់១',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '351400',
                'land_filed_fee'  => '22800',
                'total_fee'  => '374200',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '5',
                'category_id'  => '16',
                'name'  => 'ចំណុះចាប់ពី ១៥-៣០តុ ស្ថិតក្នុងតំបន់១',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '682800',
                'land_filed_fee'  => '45000',
                'total_fee'  => '727800',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '5',
                'category_id'  => '16',
                'name'  => 'ចំណុះតិចជាង ១៥តុ ស្ថិតក្នុងតំបន់២',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '227600',
                'land_filed_fee'  => '15200',
                'total_fee'  => '242800',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '5',
                'category_id'  => '16',
                'name'  => 'ចំណុះចាប់ពី ១៥-៣០តុ ស្ថិតក្នុងតំបន់២',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '455200',
                'land_filed_fee'  => '30000',
                'total_fee'  => '485200',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '5',
                'category_id'  => '17',
                'name'  => 'ចំណុះតិចជាង ២០០នាក់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '368000',
                'land_filed_fee'  => '48000',
                'total_fee'  => '416000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '5',
                'category_id'  => '17',
                'name'  => 'ចំណុះចាប់ពី ២០០-៤០០នាក់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '735600',
                'land_filed_fee'  => '96000',
                'total_fee'  => '831600',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '5',
                'category_id'  => '17',
                'name'  => 'ចំណុះលើសបី ៤០០នាក់ឡើង (គិតចំនួនកៅអី)',
                'unit'  => '៛/កៅអី.ខែ',
                'monthly_fee'  => '2800',
                'land_filed_fee'  => '400',
                'total_fee'  => '3200',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '5',
                'category_id'  => '18',
                'name'  => 'ចំណុះតិចជាង១៥០នាក់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '5147800',
                'land_filed_fee'  => '336000',
                'total_fee'  => '5483800',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '5',
                'category_id'  => '18',
                'name'  => 'ចំណុះចាប់ពី១៥០-៣០០នាក់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '6177400',
                'land_filed_fee'  => '403200',
                'total_fee'  => '6580600',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '5',
                'category_id'  => '18',
                'name'  => 'ចំណុះចាប់ពី៣០០-៤០០នាក់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '7059800',
                'land_filed_fee'  => '460800',
                'total_fee'  => '7520600',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '5',
                'category_id'  => '18',
                'name'  => 'ចំណុះលើសពី៤០០នាក់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ៖ចំនួនចំណុះ x 7520600រៀល/400',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '6',
                'category_id'  => '19',
                'name'  => 'អគារលក់ទំនិញ/ផ្សារទំនើប ស្ថិតនៅតំបន់១',
                'unit'  => '៛/ម២.ខែ',
                'monthly_fee'  => '2400',
                'land_filed_fee'  => '400',
                'total_fee'  => '2800',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '6',
                'category_id'  => '19',
                'name'  => 'អគារលក់ទំនិញ/ផ្សារទំនើប ស្ថិតនៅតំបន់២',
                'unit'  => '៛/ម២.ខែ',
                'monthly_fee'  => '1900',
                'land_filed_fee'  => '300',
                'total_fee'  => '2200',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '6',
                'category_id'  => '20',
                'name'  => 'ផ្សារ',
                'unit'  => '៛/ម២.ខែ',
                'monthly_fee'  => '1700',
                'land_filed_fee'  => '300',
                'total_fee'  => '2000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '6',
                'category_id'  => '21',
                'name'  => 'ហាងទំនិញធម្មតា ស្ថិតនៅតំបន់១',
                'unit'  => '៛/ម២.ខែ',
                'monthly_fee'  => '1200',
                'land_filed_fee'  => '400',
                'total_fee'  => '1600',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '6',
                'category_id'  => '21',
                'name'  => 'ហាងទំនិញធម្មតា ស្ថិតនៅតំបន់២',
                'unit'  => '៛/ម២.ខែ',
                'monthly_fee'  => '900',
                'land_filed_fee'  => '300',
                'total_fee'  => '1200',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '6',
                'category_id'  => '21',
                'name'  => 'មីនីម៉ាត ស្ថិតនៅតំបន់១',
                'unit'  => '៛/ម២.ខែ',
                'monthly_fee'  => '1800',
                'land_filed_fee'  => '600',
                'total_fee'  => '2400',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '6',
                'category_id'  => '21',
                'name'  => 'មីនីម៉ាត ស្ថិតនៅតំបន់២',
                'unit'  => '៛/ម២.ខែ',
                'monthly_fee'  => '1200',
                'land_filed_fee'  => '400',
                'total_fee'  => '1600',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '6',
                'category_id'  => '22',
                'name'  => 'អគារពាណិជ្ជកម្ម ស្ថិតនៅតំបន់១',
                'unit'  => '៛/ម២.ខែ',
                'monthly_fee'  => '1600',
                'land_filed_fee'  => '400',
                'total_fee'  => '2000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '6',
                'category_id'  => '22',
                'name'  => 'អគារពាណិជ្ជកម្ម ស្ថិតនៅតំបន់២',
                'unit'  => '៛/ម២.ខែ',
                'monthly_fee'  => '1200',
                'land_filed_fee'  => '300',
                'total_fee'  => '1500',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '7',
                'category_id'  => '23',
                'name'  => 'មន្ទីរពេទ្យ',
                'unit'  => '៛/គ្រែ.ខែ',
                'monthly_fee'  => '9600',
                'land_filed_fee'  => '1400',
                'total_fee'  => '11000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '7',
                'category_id'  => '24',
                'name'  => 'មន្ទីរពេទ្យសម្រាកព្យាបាលជំងឺ',
                'unit'  => '៛/គ្រែ.ខែ',
                'monthly_fee'  => '9600',
                'land_filed_fee'  => '1400',
                'total_fee'  => '11000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '7',
                'category_id'  => '25',
                'name'  => 'បន្ទប់ពិគ្រោះជំងឺ',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '27800',
                'land_filed_fee'  => '3800',
                'total_fee'  => '31600',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '8',
                'category_id'  => '26',
                'name'  => 'តិចជាង១០ បន្ទប់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '163900',
                'land_filed_fee'  => '35600',
                'total_fee'  => '199500',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '8',
                'category_id'  => '26',
                'name'  => 'ចាប់ពី១០-៣០បន្ទប់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '327700',
                'land_filed_fee'  => '71300',
                'total_fee'  => '399000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '8',
                'category_id'  => '26',
                'name'  => 'ច្រើនជាង៣០បន្ទប់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '8',
                'category_id'  => '27',
                'name'  => 'តិចជាង១០ បន្ទប់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '130800',
                'land_filed_fee'  => '28400',
                'total_fee'  => '159200',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '8',
                'category_id'  => '27',
                'name'  => 'ចាប់ពី១០-៣០បន្ទប់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '327600',
                'land_filed_fee'  => '71300',
                'total_fee'  => '398900',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '8',
                'category_id'  => '27',
                'name'  => 'ច្រើនជាង៣០បន្ទប់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '8',
                'category_id'  => '28',
                'name'  => 'តិចជាង១០ បន្ទប់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '65900',
                'land_filed_fee'  => '14400',
                'total_fee'  => '80300',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '8',
                'category_id'  => '28',
                'name'  => 'ចាប់ពី១០បន្ទប់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '8',
                'category_id'  => '29',
                'name'  => 'តិចជាង១០ បន្ទប់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '378700',
                'land_filed_fee'  => '32900',
                'total_fee'  => '411600',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '8',
                'category_id'  => '29',
                'name'  => 'ចាប់ពី១០-២០បន្ទប់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '744700',
                'land_filed_fee'  => '64800',
                'total_fee'  => '809500',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '8',
                'category_id'  => '29',
                'name'  => 'ច្រើនជាង២០បន្ទប់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '9',
                'category_id'  => '30',
                'name'  => 'សាលាចំណេះទូទៅ',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '118700',
                'land_filed_fee'  => '31000',
                'total_fee'  => '149700',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '10',
                'category_id'  => '31',
                'name'  => 'បុគ្កលិកតិចជាង​ ១៥នាក់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '131200',
                'land_filed_fee'  => '8800',
                'total_fee'  => '140000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '10',
                'category_id'  => '31',
                'name'  => 'បុគ្គលិកចាប់ពី ១៥-៥០នក់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '436800',
                'land_filed_fee'  => '28800',
                'total_fee'  => '465600',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '10',
                'category_id'  => '31',
                'name'  => 'បុគ្គលិកចាប់ពី ៥០នាក់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '10',
                'category_id'  => '32',
                'name'  => 'បុគ្កលិកតិចជាង​ ១៥នាក់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '534600',
                'land_filed_fee'  => '35400',
                'total_fee'  => '570000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '10',
                'category_id'  => '32',
                'name'  => 'បុគ្គលិកចាប់ពី ២៥-៥០នក់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '1068600',
                'land_filed_fee'  => '70200',
                'total_fee'  => '1138800',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '10',
                'category_id'  => '32',
                'name'  => 'បុគ្គលិកចាប់ពី ៥០នាក់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '11',
                'category_id'  => '33',
                'name'  => 'មានតែកន្លែងចាក់ប្រេង និងប្តូរប្រេង',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '125200',
                'land_filed_fee'  => '8400',
                'total_fee'  => '133600',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '11',
                'category_id'  => '33',
                'name'  => 'មានកន្លែងចាក់ប្រេង ប្តូរប្រេង និងមីនីម៉ាត ឫ ហាងកាហ្វេ',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '303600',
                'land_filed_fee'  => '20000',
                'total_fee'  => '323600',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '11',
                'category_id'  => '33',
                'name'  => 'មានកន្លែងចាក់ប្រេង ប្តូរប្រេង និងមីនីម៉ាត និង ហាងកាហ្វេ',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '455400',
                'land_filed_fee'  => '30000',
                'total_fee'  => '485400',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '11',
                'category_id'  => '33',
                'name'  => 'មានកន្លែងចាក់ប្រេង ប្តូរប្រេង និងមីនីម៉ាត ហាងកាហ្វេ  និងភោជនីយដ្ឋាន',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '607200',
                'land_filed_fee'  => '40000',
                'total_fee'  => '647200',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '34',
                'name'  => 'កំពង់ផែ',
                'unit'  => '៛/ម២.ខែ',
                'monthly_fee'  => '2800',
                'land_filed_fee'  => '400',
                'total_fee'  => '3200',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '35',
                'name'  => 'ស្ថានីយរថភ្លើង',
                'unit'  => '៛/ម២.ខែ',
                'monthly_fee'  => '2800',
                'land_filed_fee'  => '400',
                'total_fee'  => '3200',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '36',
                'name'  => 'ចំណតថយន្តអ្នកដំណើរ',
                'unit'  => '៛/ម២.ខែ',
                'monthly_fee'  => '2800',
                'land_filed_fee'  => '400',
                'total_fee'  => '3200',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '37',
                'name'  => 'ព្រលាបយន្តហោះ',
                'unit'  => '៛/ម២.ខែ',
                'monthly_fee'  => '4000',
                'land_filed_fee'  => '400',
                'total_fee'  => '4400',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '38',
                'name'  => 'ទំហំតូចជាង 10000m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '735600',
                'land_filed_fee'  => '48000',
                'total_fee'  => '783600',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '38',
                'name'  => 'ទំហំចាប់ពីរ 10000m2-20000m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '1470800',
                'land_filed_fee'  => '96000',
                'total_fee'  => '1566800',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '38',
                'name'  => 'ទំហំធំជាង20000m2',
                'unit'  => '៛/ម២.ខែ',
                'monthly_fee'  => '700',
                'land_filed_fee'  => '300',
                'total_fee'  => '1000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '39',
                'name'  => 'ទំហំតូចជាង 300m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '110400',
                'land_filed_fee'  => '7200',
                'total_fee'  => '117600',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '39',
                'name'  => 'ទំហំចាប់ពីរ 300m2-600m2',
                'unit'  => '៛/ម២.ខែ',
                'monthly_fee'  => '220800',
                'land_filed_fee'  => '14400',
                'total_fee'  => '235200',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '39',
                'name'  => 'ទំហំធំជាង600m2',
                'unit'  => '៛/ម២.ខែ',
                'monthly_fee'  => '400',
                'land_filed_fee'  => '400',
                'total_fee'  => '800',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '40',
                'name'  => 'ទំហំតូចជាង 500m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '80000',
                'land_filed_fee'  => '20000',
                'total_fee'  => '100000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '40',
                'name'  => 'ទំហំចាប់ពី 500-2000m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '160000',
                'land_filed_fee'  => '40000',
                'total_fee'  => '200000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '40',
                'name'  => 'ទំហំធំចាប់ពី 2000-5000m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '320000',
                'land_filed_fee'  => '80000',
                'total_fee'  => '400000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '40',
                'name'  => 'ទំហំចាប់ពី 5000-10000m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '800000',
                'land_filed_fee'  => '200000',
                'total_fee'  => '1000000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '40',
                'name'  => 'ទំហំធំជាង 10000m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '960000',
                'land_filed_fee'  => '240000',
                'total_fee'  => '1200000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '41',
                'name'  => 'ម៉ាស៊ីនលាយបេតុង១',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '800000',
                'land_filed_fee'  => '200000',
                'total_fee'  => '1000000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '41',
                'name'  => 'ម៉ាស៊ីនលាយបេតុង២',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '1200000',
                'land_filed_fee'  => '300000',
                'total_fee'  => '1500000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '41',
                'name'  => 'ម៉ាស៊ីនលាយបេតុង៣',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '1280000',
                'land_filed_fee'  => '320000',
                'total_fee'  => '1600000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '41',
                'name'  => 'ម៉ាស៊ីនលាយបេតុងលើសពី៣',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '1600000',
                'land_filed_fee'  => '400000',
                'total_fee'  => '2000000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '42',
                'name'  => 'ពោងស្តុកតិចជាង ៣',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '662000',
                'land_filed_fee'  => '43200',
                'total_fee'  => '705200',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '42',
                'name'  => 'ពោងស្តុកចាប់ពី ៣ទៅ៤',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '1324000',
                'land_filed_fee'  => '86400',
                'total_fee'  => '1410400',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '42',
                'name'  => 'ហាងស្តុកលើសពី ៤',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '43',
                'name'  => 'ទំហំធំជាង500m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '147200',
                'land_filed_fee'  => '9600',
                'total_fee'  => '156800',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '43',
                'name'  => 'ទំហំចាប់ពីរ 500m2-600m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '331200',
                'land_filed_fee'  => '21600',
                'total_fee'  => '352800',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '43',
                'name'  => 'ទំហំធំជាង600m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '300',
                'land_filed_fee'  => '300',
                'total_fee'  => '600',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '44',
                'name'  => 'ទំហំធំជាង200m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '64400',
                'land_filed_fee'  => '4400',
                'total_fee'  => '68800',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '44',
                'name'  => 'ទំហំចាប់ពីរ 200-400m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '128800',
                'land_filed_fee'  => '8400',
                'total_fee'  => '137200',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '12',
                'category_id'  => '44',
                'name'  => 'ទំហំធំជាង400m2',
                'unit'  => '៛/ម២.ខែ',
                'monthly_fee'  => '300',
                'land_filed_fee'  => '300',
                'total_fee'  => '600',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '13',
                'category_id'  => '45',
                'name'  => 'កម្មករ/បុគ្គលិកក្រោម ២៥០នាក់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '1149000',
                'land_filed_fee'  => '75000',
                'total_fee'  => '1224000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '13',
                'category_id'  => '45',
                'name'  => 'កម្មករ/បុគ្គលិកក្រោម ២៥០-៥០០នាក់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '2298000',
                'land_filed_fee'  => '150000',
                'total_fee'  => '2448000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '13',
                'category_id'  => '45',
                'name'  => 'កម្មករ/បុគ្គលិកចាប់ពី ៥០០នាក់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '13',
                'category_id'  => '46',
                'name'  => 'កម្មករ/បុគ្គលិកក្រោម ២០នាក់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '90000',
                'land_filed_fee'  => '10000',
                'total_fee'  => '100000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '13',
                'category_id'  => '46',
                'name'  => 'កម្មករ/បុគ្គលិកចាប់ពី ២០នាក់ទៅ៥០នាក់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '184000',
                'land_filed_fee'  => '12000',
                'total_fee'  => '196000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '13',
                'category_id'  => '46',
                'name'  => 'កម្មករ/បុគ្គលិកចាប់ពី ៥០នាក់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '14',
                'category_id'  => '47',
                'name'  => 'តូចជាង 1200m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '150000',
                'land_filed_fee'  => '10000',
                'total_fee'  => '160000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '14',
                'category_id'  => '47',
                'name'  => 'ចាប់ពី 1200m2',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '230000',
                'land_filed_fee'  => '20000',
                'total_fee'  => '250000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '14',
                'category_id'  => '48',
                'name'  => 'អង្គការមិនមែនរដ្ឋាភិបាល',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '55200',
                'land_filed_fee'  => '3600',
                'total_fee'  => '58800',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '15',
                'category_id'  => '49',
                'name'  => 'មន្ទីរ អង្គភាពរដ្ឋ',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '92000',
                'land_filed_fee'  => '12000',
                'total_fee'  => '104000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '16',
                'category_id'  => '50',
                'name'  => 'កម្មវិធីអ្នកចូលរួមតិចជាង ១០០០នាក់/ថ្ងៃ',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '368000',
                'land_filed_fee'  => '24000',
                'total_fee'  => '392000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '16',
                'category_id'  => '50',
                'name'  => 'កម្មវិធីអ្នកចូលរួមចាប់ពី ១០០០-១៥០០នាក/ថ្ងៃ',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '551600',
                'land_filed_fee'  => '36000',
                'total_fee'  => '587600',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '16',
                'category_id'  => '50',
                'name'  => 'កម្មវិធីអ្នកចូលរួមលើសពី ១៥០០នាក់/ថ្ងៃ',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '0',
                'land_filed_fee'  => '0',
                'total_fee'  => '0',
                'noted'  => 'សមាមាត្រ',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '16',
                'category_id'  => '50',
                'name'  => 'ការប្រគុំតន្រ្តីក្នុង១ថ្ងៃ(មិនរាប់បញ្ចូលការបោសសំអាត)',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '1103200',
                'land_filed_fee'  => '72000',
                'total_fee'  => '1175200',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '16',
                'category_id'  => '50',
                'name'  => 'ការរៀបចំពិធីមង្គលការ (បង់សេវាពេលសុំច្បាប់រៀបអាពាហ៍ពិពាហ៍)ក្រោម៥០តុ',
                'unit'  => '៛/លើក',
                'monthly_fee'  => '400000',
                'land_filed_fee'  => '24000',
                'total_fee'  => '424000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '16',
                'category_id'  => '51',
                'name'  => 'ការលក់ដូរផ្សេងៗតាមដងផ្លូវ(អាចម៉ៅការឱ្យប្រមូល)',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '500',
                'land_filed_fee'  => '500',
                'total_fee'  => '1000',
                'noted'  => '',
                'created_by'  => '1',
            ],
            [
                'user_id'  => '1',
                'branch_id'  => '1',
                'business_type_id'  => '16',
                'category_id'  => '52',
                'name'  => 'បញ្ចេញសំរាម សំណល់រឹង ចេញពីការដ្ឋានដោយប្រើប្រាស់ ក្រុមហ៊ុនផ្តល់',
                'unit'  => '៛/ខែ',
                'monthly_fee'  => '176200',
                'land_filed_fee'  => '23000',
                'total_fee'  => '199200',
                'noted'  => '',
                'created_by'  => '1',
            ],
        ];
        foreach ($data as $value) {
            SubCategory::firstOrCreate($value);
        }
    }
}
